### ISSUE TITLE
pretrained pth

### ISSUE THREAD

**Issue by youthong** [NICE-FUTURE/FET-FGVC#2]
I want to train my model in a new dataset, but I cant find the pretrained weights. Can you provide the pre-trained weights file? Thanks

**Comment by NICE-FUTURE** [comment]
https://github.com/NICE-FUTURE/FET-FGVC/blob/b8e20b2846875fb6ea189477500be2ff1c3d37b7/network/GlobalBranch.py#L16-L20

The pretrained weights I used are the official weights of the backbones. So you can find the corresponding weights in their official repository.

For convenience, I have uploaded those three weights to current repository. Please visit the [Release Page](https://github.com/NICE-FUTURE/FET-FGVC/releases).
